import type { Metadata } from 'next'
import { twMerge } from 'tailwind-merge'

import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={twMerge('min-h-screen bg-background font-sans antialiased', inter.variable)}>{children}</body>
    </html>
  )
}
